### ISSUE TITLE
consider scss/operator-no-newline-after

### ISSUE THREAD

**Issue by nswaldman** [mediamonks/stylelint-config#162]
When writing sufficiently long lines of scss with operators, our Prettier config will split this up into multiple lines for legibility. This then collides with our stylelint-config's [scss/operator-no-newline-after][1]:

```
calc(#{$from} + #{strip-unit($to - $from)} * ((100vw - #{$minVw}) / #{strip-unit($maxVw - $minVw)})),
```
becomes
```
calc(#{$from} + 
  #{strip-unit($to - $from)} * 
  ((100vw - #{$minVw}) / #{strip-unit($maxVw - $minVw)})),
```

I wouldn't mind having this around as a warning, personally. Thoughts appreciated.

[1]: https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/operator-no-newline-after/README.md

**Comment by ReneDrie** [comment]
This even comes with impossible scenario's (or at least not ones I know how to fix).
Where prettier splits it, but eslint doesn't approve that (or vice versa). So I agree

**Comment by nswaldman** [comment]
For now I worked around that by putting `// prettier-ignore` before the affected node. It would be nice not to though.

**Comment by ThaNarie** [comment]
IMO we should always disable eslint/stylelint rules that prettier handles/fixes.

> I wouldn't mind having this around as a warning, personally.

Why would you want that? It's not that you can action that in any way.
Or are there scenarios where you could mess up something like that yourself without prettier having anything to do with it?
